# Generated by Django 3.1.6 on 2021-02-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210217_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_on',
            new_name='post',
        ),
    ]
